### ISSUE TITLE
AI builder in PowerApps 

### ISSUE THREAD

**Issue by SomyGit** [brisbanebootcamp/BrisbaneAI-UG#4]
A brief on Azure Cognitive Services and a new Power Platform capability called AI Builder that is directly integrated into PowerApps and Power Automate. It will enable us to build more intelligent applications and to improve business performance through a point-and-click experience.

**Comment by jernejk** [comment]
Thank you @SomyGit, your presentation was great! 😊

The recording to the session available on YouTube: https://youtu.be/y8Ud4JBBBkQ
